export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// export const SET_CURRENT_USER = 'FETCH_REVIEWS_FULFILLED';
// export const SET_CURRENT_USER = 'FETCH_REVIEWS_REJECTED';
// export const SET_CURRENT_USER = 'POST_REVIEW_FULFILLED';
// export const SET_CURRENT_USER = 'POST_REVIEW_REJECTED';
// export const SET_CURRENT_USER = 'POST_RATING_FULFILLED';
// export const SET_CURRENT_USER = 'POST_REVIEW_FULFILLED';
// export const SET_CURRENT_USER = 'POST_RATING_REJECTED';